export const Data = {
  newsList: {
    status: "ok",
    total_hits: 10000,
    page: 1,
    total_pages: 200,
    page_size: 50,
    articles: [
      {
        title: "Updated 2023 NFL draft order after Week 15",
        author: "Alyssa Barbieri",
        published_date: "2022-12-20 12:30:27",
        published_date_precision: "full",
        link: "https://sports.yahoo.com/updated-2023-nfl-draft-order-123027799.html?src=rss",
        clean_url: "yahoo.com",
        excerpt:
          "Here's a look at the updated 2023 NFL draft order following Week 15 action:",
        summary:
          "Week 15 of the 2022 NFL season is in the books, which featured another thrilling slate of action. With just three weeks left in the regular season, the draft order is starting to become clear for some teams, but there's still plenty of shakeup.\nFans of the Broncos and Rams aren't sitting pretty as they've already dealt their 2023 first-round selections to the Seahawks and Lions, respectively. Meanwhile, fans of the Texans and Bears should be excited about what's shaping up to be a top-3 selection for their teams.",
        rights: "yahoo.com",
        rank: 31,
        topic: "sport",
        country: "US",
        language: null,
        authors: "Alyssa Barbieri",
        media:
          "https://s.yimg.com/ny/api/res/1.2/SqLWBLKHC3p6M9o.Hc41dg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD03MjA-/https://media.zenfs.com/en/chicago_bears_wire_usa_today_sports_articles_533/8c965812ef556ad5f4428afa1f0c7eb7",
        is_opinion: false,
        twitter_account: "@Yahoo",
        _score: 7.501598,
        _id: "88e56acc421939d240e71e62fa53a407",
      },
      {
        title:
          "SEC football recruiting rankings following the early signing period",
        author: "Stacey Blackwood",
        published_date: "2022-12-24 15:15:26",
        published_date_precision: "full",
        link: "https://sports.yahoo.com/sec-football-recruiting-rankings-following-151526778.html?src=rss",
        clean_url: "yahoo.com",
        excerpt:
          "A look at the 2023 SEC football recruiting rankings following the early signing period.",
        summary:
          "Now that the madness of the early signing period has simmered down a bit, it is time to take a peek at how the rankings look for the football programs in the SEC.\nTo the surprise of no one, Nick Saban and the Alabama Crimson Tide have a solid grasp on the SEC's and the nation's top class followed by Kirby Smart and the Georgia Bulldogs.\nA total of 10 SEC teams landed inside the top 25 according to On3's Consensus Football Team Rankings including four inside the top 10 nationally.\nHere is how the SEC recruiting rankings line up following the early signing period according to On3.",
        rights: "yahoo.com",
        rank: 31,
        topic: "sport",
        country: "US",
        language: "en",
        authors: "Stacey Blackwood",
        media:
          "https://s.yimg.com/ny/api/res/1.2/JdUOcPjlWXo.G1L.SVkoqQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MTU-/https://media.zenfs.com/en/roll_tide_wire_usa_today_articles_214/63521df49f0b26e87edc3f0977e61875",
        is_opinion: false,
        twitter_account: "@Yahoo",
        _score: 7.380086,
        _id: "314c5706b1c64688047d6caece59ebf0",
      },
      {
        title: "How former Alabama players performed in the NFL in Week 15",
        author: "Brody Smoot",
        published_date: "2022-12-20 19:06:26",
        published_date_precision: "timezone unknown",
        link: "https://rolltidewire.usatoday.com/lists/alabama-in-nfl-how-former-alabama-players-performed-in-the-nfl-in-week-14/",
        clean_url: "usatoday.com",
        excerpt:
          "Alabama has been well-represented at the professional level by players that began their careers in Tuscaloosa. On Sunday, the Tide broke a record for the most players to play in the NFL from one…",
        summary:
          "Terms of UsePrivacy PolicyDo Not Sell My InfoHelp CenterAboutUSA TODAY Sports Media GroupScott Galvin-USA TODAY SportsAlabama has been well-represented at the professional level by players that began their careers in Tuscaloosa. On Sunday, the Tide broke a record for the most players to play in the NFL from one program in a season.That speaks to the culture and foundation that Alabama head coach Nick Saban has established. Times have changed, but the Crimson Tide faithful will likely always be able to see their former favorite players contributing in a positive way to their NFL team's successes.",
        rights: "newsbreak.com",
        rank: 126,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Brody Smoot",
        media:
          "https://img.particlenews.com/img/id/4aYBY4_0jp9Fmfu00?type=thumbnail_1200x627&limit=20",
        is_opinion: false,
        twitter_account: "@newsbreak",
        _score: 7.361251,
        _id: "51f8547843d9e324e96712bb02be348b",
      },
      {
        title:
          "Horoscope Today, December 21, 2022: Free online Astrological prediction for all zodiac signs",
        author: "Chirag Daruwala",
        published_date: "2022-12-21 03:58:31",
        published_date_precision: "full",
        link: "https://www.timesnownews.com/astrology/horoscope-today-astrological-prediction-for-december-21-2022-article-96387097",
        clean_url: "timesnownews.com",
        excerpt:
          "Today's Horoscope and Astrology Predictions Free, December 21, 2022: Every day presents its own set of possibilities, therefore proper planning is required before making a decision. Before beginning…",
        summary:
          "Horoscope Today Online, December 21, 2022: Astrological prediction for all zodiac signs freePhoto : iStockAre you curious as to what awaits you today? Should you finally say yes to an investment opportunity? Will you be able to purchase your dream home? Is today going to be a good day? Here are the horoscope and astrology predictions for all zodiac signs. ARIES (Mar 21-Apr 20)Lucky Number: 09Lucky Colour: GreenLove Life: Whatever innovation your partner starts today, they will have your full support.",
        rights: "timesnownews.com",
        rank: 3465,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "Chirag Daruwala,Debosmita Ghosh",
        media:
          "https://static.tnn.in/thumb/msid-96387097,imgsize-100,updatedat-1671595111014,width-1280,height-720,resizemode-75/96387097.jpg",
        is_opinion: false,
        twitter_account: "TIMESNOW",
        _score: 7.3603187,
        _id: "d16c4bc19e6092d1b6e63e9d7ad0ebd6",
      },
      {
        title:
          "Horoscope 19 December : वृश्चिक राशीच्या लोकांनी भरपूर गुंतवणूक करावी, जाणून घ्या तुमचा दिवस कसा जाईल",
        author: "Bureau",
        published_date: "2022-12-19 01:14:36",
        published_date_precision: "full",
        link: "https://zeenews.india.com/marathi/spirituality/today-horoscope-19-december-2022-daily-rashi-bhavishya-and-today-rashi-bhavishya-nmp/676512",
        clean_url: "india.com",
        excerpt:
          "Today Horoscope 19 December : आज 19 डिसेंबर, सोमवार आहे. कसा जाईल तुमचा आजचा दिवस, तुमच्या ताऱ्यांची हालचाल काय आहे आणि त्याचा तुमच्यावर कसा परिणाम होईल, जाणून घेऊयात",
        summary:
          "Today Horoscope 19 December : आज 19 डिसेंबर, सोमवार आहे. कसा जाईल तुमचा आजचा दिवस, तुमच्या ताऱ्यांची हालचाल काय आहे आणि त्याचा तुमच्यावर कसा परिणाम होईल, जाणून घेऊयात\n Updated: Dec 19, 2022, 06:44 AM IST Today Horoscope 19 December 2022 daily rashi bhavishya and today rashi bhavishya nmp Horoscope 19 December 2022 : आज सोमवार...दिवसाची सुरुवात झालीये, काहीजण त्यांच्यात्यांच्या कामासाठी निघाले आहेत. तुम्ही दिवसाची सुरुवात केली असेल किंवा नसेल, तरीही पाहून घ्या काय सांगतं आजचं राशीभविष्य... \nमेष (Aries Horoscope Today) - वैवागहिक जीवनात सुधारणा होईल आणि नोकरीत आज प्रगती होईल.",
        rights: "india.com",
        rank: 2337,
        topic: "news",
        country: "IN",
        language: "mr",
        authors: "Bureau",
        media:
          "https://marathi.cdn.zeenews.com/marathi/sites/default/files/2022/12/19/546485-today-horoscope-19-december-2022-daily-rashi-bhavishya-and-today-rashi-bhavishya-nmp.png",
        is_opinion: false,
        twitter_account: "@zee24taasnews",
        _score: 7.3534493,
        _id: "5f89c603eb4ecbd6b3b53603f21bc893",
      },
      {
        title: "Where Titans stand in AFC South, playoff picture after Week 15",
        author: "Mike Moraitis",
        published_date: "2022-12-19 08:17:19",
        published_date_precision: "full",
        link: "https://titanswire.usatoday.com/lists/where-titans-stand-in-afc-south-playoff-picture-after-week-15/",
        clean_url: "usatoday.com",
        excerpt:
          "The Titans' once-comfortable lead in the AFC South has dwindled down to one game.",
        summary:
          "The Tennessee Titans' once-comfortable lead in the AFC South is now quite the opposite after suffering their fourth-straight loss to the Los Angeles Chargers on Sunday.\nIn tandem with that loss, the Jacksonville Jaguars pulled off a stunning win over the Dallas Cowboys in overtime after trailing 21-7 going into halftime.\nBuy Titans Tickets\nThanks, Cowboys.\nWith the Titans loss and Jaguars win, Jacksonville is now one game back of Tennessee thanks to having the head-to-head tie-breaker. These two teams meet once again in Week 18, by the way.",
        rights: "usatoday.com",
        rank: 126,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Am Et,Mike Moraitis,Shaun Calderon",
        media:
          "https://titanswire.usatoday.com/wp-content/uploads/sites/43/2022/12/USATSI_19650145-1.jpg?w=1024&h=576&crop=1",
        is_opinion: false,
        twitter_account: "@MichaelMoraitis",
        _score: 7.3527884,
        _id: "e94cee310624766dc27ff29b32880770",
      },
      {
        title:
          "NFL power rankings: How far do the Bucs fall heading into Week 16?",
        author: "Luke Easterling",
        published_date: "2022-12-21 10:15:19",
        published_date_precision: "full",
        link: "https://bucswire.usatoday.com/lists/nfl-power-rankings-week-16-tampa-bay-buccaneers-tom-brady/",
        clean_url: "usatoday.com",
        excerpt:
          "See where the Tampa Bay Buccaneers land in the latest NFL power rankings heading into Week 16",
        summary:
          "Another week, another embarrassing loss for the Tampa Bay Buccaneers, who followed up a blowout against the San Francisco 49ers by squandering a 17-point lead and giving up 34 straight points Sunday to the Cincinnati Bengals.Despite those back-to-back crushing defeats, the Bucs remain in first place in the dismal NFC South, and still control their destiny to be the No. 4 seed in the NFC playoffs with three games left in the regular season.Tampa Bay could even lose this week's game against the Arizona Cardinals and still win the division by beating the Carolina Panthers and Atlanta Falcons to close out the year.",
        rights: "usatoday.com",
        rank: 126,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Am Et,Luke Easterling",
        media:
          "https://bucswire.usatoday.com/wp-content/uploads/sites/50/2022/12/USATSI_19650256.jpg?w=1024&h=576&crop=1",
        is_opinion: false,
        twitter_account: null,
        _score: 7.350374,
        _id: "b7502aea73751ed9cbbcb0982425eeeb",
      },
      {
        title:
          "Where is Oklahoma in the 247Sports team rankings ahead of the early signing period?",
        author: "John Williams",
        published_date: "2022-12-20 15:56:47",
        published_date_precision: "full",
        link: "https://sports.yahoo.com/where-oklahoma-247sports-team-rankings-155647020.html?src=rss",
        clean_url: "yahoo.com",
        excerpt:
          "Ahead of the opening of the early signing period, where do the Oklahoma Sooners rank in 247Sports team recruiting rankings?",
        summary:
          "Starting Wednesday Dec. 21, the Oklahoma Sooners will begin to officially welcome their 2023 recruiting class to the crimson and cream.\nThe next wave of Oklahoma Sooners will sign their national letters of intent. Many will finalize their commitments during the early signing period, which runs through Dec. 23, and a few will wait until February's national signing day.\nThe Oklahoma Sooners are still looking to close strong on several recruitments. Though Peyton Bowen and Tausili Akana look like they're trending to Oklahoma, nothing's final until it's final.",
        rights: "yahoo.com",
        rank: 31,
        topic: "sport",
        country: "US",
        language: "en",
        authors: "John Williams",
        media:
          "https://s.yimg.com/ny/api/res/1.2/f3kai2Db23Az4ZMPeChzWQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/sooners_wire_usa_today_articles_466/5ff8217c547f12fcd8d4473d9a68f8d9",
        is_opinion: false,
        twitter_account: "@Yahoo",
        _score: 7.3401117,
        _id: "ad0a071ee2f3f0f349cdfe141500d110",
      },
      {
        title:
          "Horoscope Today, December 22, 2022: Free online Astrological prediction for all zodiac signs",
        author: "Chirag Daruwala",
        published_date: "2022-12-22 01:36:29",
        published_date_precision: "full",
        link: "https://www.timesnownews.com/astrology/horoscope-today-december-22-2022-free-online-astrological-prediction-for-all-zodiac-signs-article-96411811",
        clean_url: "timesnownews.com",
        excerpt:
          "Today's Horoscope and Astrology Predictions Free, December 22, 2022: Every day presents its own set of possibilities, therefore proper planning is required before making a decision. Before beginning…",
        summary:
          "Horoscope Today Online, December 22, 2022: Astrological prediction for all zodiac signs frePhoto : iStockAre you curious as to what awaits you today? Should you finally say yes to an investment opportunity? Will you be able to purchase your dream home? Is today going to be a good day? Here are the horoscope and astrology predictions for all zodiac signs. ARIES (Mar 21-Apr 20)Lucky Number: 09Lucky Colour: CreamLove Life: You and your partner will work together today to achieve a shared objective, and you will be able to envision your destiny united.",
        rights: "timesnownews.com",
        rank: 3465,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "Chirag Daruwala,Debosmita Ghosh",
        media:
          "https://static.tnn.in/thumb/msid-96411811,imgsize-100,updatedat-1671672989742,width-1280,height-720,resizemode-75/96411811.jpg",
        is_opinion: false,
        twitter_account: "@TIMESNOW",
        _score: 7.3278103,
        _id: "ebfbcae477977f70aa14553b8d82e089",
      },
      {
        title:
          "247Sports' 2023 recruiting class rankings top 25 after early signing day",
        author: "Adam Dubbin",
        published_date: "2022-12-24 08:38:22",
        published_date_precision: "full",
        link: "https://gatorswire.usatoday.com/lists/college-football-recruiting-247sports-rankings-2023-early-signing-day/",
        clean_url: "usatoday.com",
        excerpt:
          "Take a look at the top 25 schools in 247Sports' updated 2023 recruiting rankings.",
        summary:
          "Early signing day 2022 has come and gone, and while the early signing period remains open, enough of the dust has settled to get a good idea of what each school accomplished in the 2023 recruiting cycle so far.Among the publications tracking the progress of each respective program is 247Sports, which has updated its recruiting rankings accordingly now that the ink has been put to paper by a majority of recruits.Take a look below at 247Sports' new top 25 after being updated to reflect the recent signings as of Saturday morning.",
        rights: "usatoday.com",
        rank: 126,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Adam Dubbin,Am Et,David Rosenberg,Pat Dooley",
        media:
          "https://gatorswire.usatoday.com/wp-content/uploads/sites/7/2020/10/USATSI_14703829.jpg?w=1024&h=576&crop=1",
        is_opinion: false,
        twitter_account: null,
        _score: 7.3266273,
        _id: "87f1928c863dbf74093ad95c6d7f0d83",
      },
      {
        title:
          "Horoscope Today, December 24, 2022: Free online Astrological prediction for all zodiac signs",
        author: "Chirag Daruwala",
        published_date: "2022-12-24 00:50:33",
        published_date_precision: "full",
        link: "https://www.timesnownews.com/astrology/horoscope-today-december-24-2022-free-online-astrological-prediction-for-all-zodiac-signs-article-96468189",
        clean_url: "timesnownews.com",
        excerpt:
          "Today's Horoscope and Astrology Predictions Free, December 24, 2022: Every day presents its own set of possibilities, therefore proper planning is required before making a decision. Before beginning…",
        summary:
          "Horoscope Today Online, December 24, 2022: Astrological prediction for all zodiac signs freePhoto : iStockAre you curious as to what awaits you today? Should you finally say yes to an investment opportunity? Will you be able to purchase your dream home? Is today going to be a good day? Here are the horoscope and astrology predictions for all zodiac signs.ARIES (Mar 21-Apr 20)Lucky Number: 09Lucky Colour: CreamLove Life: If you're married, you'll be capable to show your partner the affection they need right now.",
        rights: "timesnownews.com",
        rank: 3465,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "Chirag Daruwala,Debosmita Ghosh",
        media:
          "https://static.tnn.in/thumb/msid-96468189,imgsize-100,updatedat-1671843033788,width-1280,height-720,resizemode-75/96468189.jpg",
        is_opinion: false,
        twitter_account: "TIMESNOW",
        _score: 7.3247886,
        _id: "964e029f58c7c9be11cdc746763296ac",
      },
      {
        title:
          "Where Ducks stand in 2023 national recruiting rankings following historic signing day",
        author: "Ducks Wire",
        published_date: "2022-12-22 13:27:27",
        published_date_precision: "full",
        link: "https://sports.yahoo.com/where-ducks-stand-2023-national-132727077.html",
        clean_url: "yahoo.com",
        excerpt:
          "Where Ducks stand in 2023 national recruiting rankings following historic signing day",
        summary:
          "Coming into the day, the Oregon Ducks had the No. 14 ranked recruiting class in the nation with hopes of moving up a few spots to get close to the top 10 in Dan Lanning's first year with the team.\nThere were a lot of great players already committed to the Ducks ready to sign, and a couple of nice pieces potentially considering a flip to Oregon. It was shaping up to be a successful day.\nThen the fireworks started to come in.\nOregon hit early and often, flipping 4-star Baylor QB Austin Novosad before the sun came up, and then later flipping 5-star safety Peyton Bowen from Notre Dame not long before they landed 5-star EDGE Matayo Uiagalele over USC and Ohio State.",
        rights: "yahoo.com",
        rank: 31,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Ducks Wire",
        media:
          "https://s.yimg.com/ny/api/res/1.2/HjwlY6Y_VOA4o.J7UGtyNQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/ducks_wire_usa_today_articles_200/9ec9445e0bf3495608150c544a605015",
        is_opinion: false,
        twitter_account: "@Yahoo",
        _score: 7.322838,
        _id: "6052d9a9b89d15c1b7d1d81f1550af84",
      },
      {
        title: "Today Rasi Palan 19th December 2022: இன்றைய ராசிபலன்",
        author: "Web Desk",
        published_date: "2022-12-19 01:31:29",
        published_date_precision: "full",
        link: "https://tamil.indianexpress.com/horoscope/rasi-palan-today-monday-19-december-2022-560938/",
        clean_url: "indianexpress.com",
        excerpt:
          "Today Rasi Palan for Monday, December 19th, 2022: இன்றைய ராசிபலன்களை நமது இந்தியன் எக்ஸ்பிரஸ் தமிழ் தளத்தில் படித்து தெரிந்துகொள்ளுங்கள்.",
        summary:
          "Rasipalan 19th December 2022, Monday ராசிபலன் டிசம்பர் 19ம் தேதி திங்கள்கிழமை 2022: ராசிபலன் ஜாதகம் அல்ல. நம் கிரக நிலைகளின் அடிப்படையில் கணிக்கப்படும் ஒரு நம்பிக்கை. நம் அன்றாட வாழ்க்கை பயணத்தில் நிகழக் கூடும் மாற்றங்களை அறியும் நம்பிக்கை இது. உங்கள் தமிழ் இந்தியன் எக்ஸ்பிரஸ் தளத்தின் மூலம் நீங்கள் உங்களது தினசரி பலனை தெரிந்து கொள்ளலாம். Today Rasi Palan 19th December 2022: இன்றைய ராசி பலன், டிசம்பர் 19ம் தேதி 2022ராசி (குறிப்பிட்ட நாட்களில் அந்த நட்சத்திரத்தில் பிறந்தவர்கள்) மேஷம் Today Rasi palan (Mesham today's Rasi Palan / மேஷம் ராசிபலன்/ Aries horoscope today) 19-12-2022 Monday சந்திரன் இப்போது உங்கள் எல்லா உறவுகளின் மீதும் உணர்ச்சிவசப்படும் நடத்தையைப் பரவலாக்குகிறது.",
        rights: "indianexpress.com",
        rank: 976,
        topic: "news",
        country: "IN",
        language: "ta",
        authors: "Web Desk,WebDesk",
        media:
          "https://tamil.indianexpress.com/wp-content/uploads/2022/12/Horoscope-11.jpg",
        is_opinion: false,
        twitter_account: "@IeTamil",
        _score: 7.309988,
        _id: "1b66c1911c87aa6949f86917d9614b28",
      },
      {
        title:
          "Where Texas' 2023 recruiting class ranks after the first day of early signing period",
        author: "Cami Griffin",
        published_date: "2022-12-21 15:05:56",
        published_date_precision: "full",
        link: "https://longhornswire.usatoday.com/lists/texas-football-recruiting-longhorns-2023-class-rankings-signees-early-signing-period-alabama-oregon-miami-georgia/",
        clean_url: "usatoday.com",
        excerpt: "Very, very impressive haul for Steve Sarkisian's staff.",
        summary:
          "The first day of the early signing period went extremely well for the Texas Longhorns.\nSteve Sarkisian's staff was able to sign all 21 commits in their 2023 recruiting class on Wednesday. The class is led by five-star quarterback Arch Manning, five-star linebacker Anthony Hill and five-star running back Cedric Baxter Jr.\nBuy Longhorns Tickets\nThe Longhorns also received somewhat of a surprise recruiting win over Oklahoma for four-star edge Tausili Akana. After Akana's commitment, Texas' 2023 recruiting class jumped one spot in 247Sports' composite team rankings.",
        rights: "usatoday.com",
        rank: 126,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Cami Griffin,Cj Mumme,Pm Ct",
        media:
          "https://longhornswire.usatoday.com/wp-content/uploads/sites/97/2022/09/USATSI_19018118-1.jpg?w=1024&h=576&crop=1",
        is_opinion: false,
        twitter_account: null,
        _score: 7.2996254,
        _id: "943f62fcef639b3d47304961c56115a2",
      },
      {
        title: "Eagles' updated 53-man roster for Week 16 matchup at Cowboys",
        author: "Glenn Erby",
        published_date: "2022-12-24 09:23:27",
        published_date_precision: "full",
        link: "https://theeagleswire.usatoday.com/lists/philadelphia-eagles-dallas-cowboys-53-man-roster-week-16-nfl/",
        clean_url: "usatoday.com",
        excerpt:
          "Here's an updated look at the Philadelphia Eagles 53-man roster ahead of Saturday afternoon's matchup against the Dallas Cowboys at AT&T Stadium",
        summary:
          "The Philadelphia Eagles are less than seven hours away from returning to the field for a late Saturday afternoon matchup against the Dallas Cowboys at AT&T Stadium.The Birds are the favorite and will look to move to 14-1 on the season while maintaining their lead in the NFC. Here's your updated 53-man roster for Week 16 with Philadelphia choosing to hold quarterback Jalen Hurts out this week. Mandatory Credit: Mike Dinovo-USA TODAY Sports\nAn MVP candidate and first-time Pro Bowler, Hurts will miss his first start of the season with a shoulder injury.",
        rights: "usatoday.com",
        rank: 126,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Am Et,Glenn Erby",
        media:
          "https://theeagleswire.usatoday.com/wp-content/uploads/sites/69/2022/12/1446761277.jpg?w=1024&h=576&crop=1",
        is_opinion: false,
        twitter_account: null,
        _score: 7.297664,
        _id: "c87dc03f52a9341fc8eb510bdbe4980f",
      },
      {
        title: "2023 NFL draft: Updated 1st-round order after Week 15",
        author: "Luke Easterling",
        published_date: "2022-12-20 17:35:48",
        published_date_precision: "full",
        link: "https://sports.yahoo.com/2023-nfl-draft-updated-1st-173548633.html",
        clean_url: "yahoo.com",
        excerpt:
          "Here's what the first-round order would look like if the 2023 NFL draft took place after Week 15",
        summary:
          "Only three weeks remain in the 2022 NFL regular season, which means the top of the 2023 NFL draft order is coming into clearer focus.\nThe one-win Houston Texans still have a two-game lead on the rest of the league for the No. 1 overall pick, but there's still plenty of time for movement throughout the rest of the top 10 selections.\nHere's what the first-round order would look like if next year's draft took place after Week 15 action (courtesy of Tankathon):\n*NOTE: The Miami Dolphins forfeited their first-round pick in next year's draft as a result of the NFL's investigation into tampering violations.",
        rights: "yahoo.com",
        rank: 31,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Luke Easterling",
        media:
          "https://s.yimg.com/ny/api/res/1.2/9aU7IOFl8oFWF0oRjCyfxw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/draft_wire_usa_today_sports_articles_126/05d5a87dbdfa8401efc0d52d35e343f6",
        is_opinion: false,
        twitter_account: "@Yahoo",
        _score: 7.2962933,
        _id: "2344843cc2eb0a563ab80183433d873d",
      },
      {
        title:
          "Horoscope Today, December 23, 2022: Free online Astrological prediction for all zodiac signs",
        author: "Chirag Daruwala",
        published_date: "2022-12-23 00:54:32",
        published_date_precision: "full",
        link: "https://www.timesnownews.com/astrology/horoscope-today-astrological-prediction-for-december-23-2022-article-96439439",
        clean_url: "timesnownews.com",
        excerpt:
          "Today's Horoscope and Astrology Predictions Free, December 23, 2022: Every day presents its own set of possibilities, therefore proper planning is required before making a decision. Before beginning…",
        summary:
          "Horoscope Today Online, December 23, 2022: Astrological prediction for all zodiac signs freePhoto : iStockAre you curious as to what awaits you today? Should you finally say yes to an investment opportunity? Will you be able to purchase your dream home? Is today going to be a good day? Here are the horoscope and astrology predictions for all zodiac signs.ARIES (Mar 21-Apr 20)Lucky Number: 21Lucky Colour: GreenLove Life: Bachelors will start looking for a romantic partner. Individuals who are currently in a connection should get prepared to undertake some important decisions about the course they want to take their connection to.",
        rights: "timesnownews.com",
        rank: 3465,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "Chirag Daruwala,Debosmita Ghosh",
        media:
          "https://static.tnn.in/thumb/msid-96439439,imgsize-100,updatedat-1671756872373,width-1280,height-720,resizemode-75/96439439.jpg",
        is_opinion: false,
        twitter_account: "TIMESNOW",
        _score: 7.29214,
        _id: "f0491f9f52e2b868c35c3a17b90f3b56",
      },
      {
        title:
          "Horoscope Today : 'या' राशीच्या लोकांचा आजचा दिवस भाग्याचा, जाणून घ्या तुमच्या राशीची स्थिती",
        author: "Bureau",
        published_date: "2022-12-23 02:24:08",
        published_date_precision: "full",
        link: "https://zeenews.india.com/marathi/spirituality/today-horoscope-23-december-2022-in-marathi/677441",
        clean_url: "india.com",
        excerpt:
          "Horoscope Today, 23 December : आजचे राशीभविष्य, शुक्रवार 23 डिसेंबर 2022 या दिवशी तुमची आर्थिक स्थिती कशी असेल आणि कोणत्या राशीमधील व्यक्तींचे चमकणार नशीब? कोणत्या राशीच्या लोकांना घ्यावी लागेल काळजी?…",
        summary:
          "Horoscope Today, 23 December : आजचे राशीभविष्य, शुक्रवार 23 डिसेंबर 2022 या दिवशी तुमची आर्थिक स्थिती कशी असेल आणि कोणत्या राशीमधील व्यक्तींचे चमकणार नशीब? कोणत्या राशीच्या लोकांना घ्यावी लागेल काळजी? जाणून घ्या शुक्रवार म्हणजेच आजच्या दिवसाचे तुमचे राशी भविष्य.\n Updated: Dec 23, 2022, 07:54 AM IST Horoscope Today 23 December 2022 in Marathi: आज शुक्रवार, 23 डिसेंबर 2022 या दिवशी तुमची आर्थिक स्थिती कशी असेल आणि कोणत्या राशीमधील व्यक्तींचे चमकणार नशीब? कोणत्या राशीच्या लोकांना घ्यावी लागेल काळजी? जाणून घ्या आजच्या दिवसाचे तुमचे राशी भविष्य.",
        rights: "india.com",
        rank: 2337,
        topic: "news",
        country: "IN",
        language: "mr",
        authors: "Bureau",
        media:
          "https://marathi.cdn.zeenews.com/marathi/sites/default/files/2022/12/23/547324-horsop.jpg",
        is_opinion: false,
        twitter_account: "@zee24taasnews",
        _score: 7.2788963,
        _id: "496d538d31d3102130db241458933e5a",
      },
      {
        title:
          "Horoscope Today, December 20: Business benefits on the cards of Taurus, Libra; know about other zodiacs",
        author: "India Tv News",
        published_date: "2022-12-19 23:45:02",
        published_date_precision: "full",
        link: "https://www.indiatvnews.com/astrology/horoscope-today-december-20-business-benefits-on-the-cards-of-taurus-libra-know-about-other-zodiacs-astrology-news-2022-12-19-832513",
        clean_url: "indiatvnews.com",
        excerpt:
          "Horoscope Today, December 20: Business benefits on the cards of Taurus, and Libra. Know about other zodiacs",
        summary:
          "Follow us on Image Source : INDIA TV Horoscope Today, December 20 Horoscope Today, December 20: Today is the Dwadashi date of Paush Krishna Paksha and Tuesday. Dwadashi Tithi will be till 12:45 tonight. Sukarma Yoga will remain till 12.41 minutes tonight. Along with this, from 9:55 in the morning to 12:45 at night, there will be a permanent Jai Yoga. Swati Nakshatra will remain till 9.55 am today, after that Vishakha Nakshatra will appear. Today is Dwadashi. Apart from this, today Rahu will enter the first phase of Bharani Nakshatra and Ketu will enter the third phase of Swati Nakshatra.",
        rights: "indiatvnews.com",
        rank: 6892,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "India TV Lifestyle Desk,India TV News,India Tv,New Delhi",
        media:
          "https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2022/12/horoscope-today-8-1671472190.jpg",
        is_opinion: false,
        twitter_account: "India TV",
        _score: 7.269166,
        _id: "24840462a675ffd8ed2542031c46b92c",
      },
      {
        title:
          "Early signing period: Ranking top 2023 football signing classes after day No. 2",
        author: "Dan Harralson",
        published_date: "2022-12-23 11:58:27",
        published_date_precision: "full",
        link: "https://news.yahoo.com/early-signing-period-ranking-top-115827750.html",
        clean_url: "yahoo.com",
        excerpt:
          "Early signing period: Ranking the top 2023 college football signing classes after day No. 2",
        summary:
          "The 2022 early signing period is taking place Dec. 21-23 for the 2023 recruiting signing class.\nThe 2022 early signing period is Josh Heupel's second as Tennessee's head coach. He was hired as the Vols' head coach in Jan. 2021.\n2022 early signing period: Tracking Tennessee's signees\n'It's been a lot of fun going through the process with these guys,' Heupel said Wednesday. 'We believe in, obviously, their athleticism but just as importantly who they are. I'd like to thank their families for entrusting us with their sons for the next three-to-five years.",
        rights: "yahoo.com",
        rank: 31,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Dan Harralson",
        media:
          "https://s.yimg.com/ny/api/res/1.2/mJCtnhGKmzCr8dfkMye3iA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/vols_wire_usa_today_articles_138/3c49cf2ce7526c8de62d8e2256938b52",
        is_opinion: false,
        twitter_account: "@YahooNews",
        _score: 7.265545,
        _id: "ba5f74a8ddc2a2ec72058ab195d0f686",
      },
      {
        title:
          "Horoscope Today, December 20: Aquarians, take risks for financial gains; predictions for all zodiac signs",
        author: "Chirag Daruwala",
        published_date: "2022-12-20 04:11:10",
        published_date_precision: "full",
        link: "https://www.timesnownews.com/astrology/horoscope-today-december-20-aquarians-take-risks-for-financial-gains-predictions-for-all-zodiac-signs-article-96359611",
        clean_url: "timesnownews.com",
        excerpt:
          "Every day presents its own set of possibilities, therefore proper planning is required before making a decision. Before beginning the planning process, you might want to read the astrological…",
        summary:
          "Horoscope today for all zodiac signs, December 20, 2022Photo : iStockAre you curious as to what awaits you today? Should you finally say yes to an investment opportunity? Will you be able to purchase your dream home? Is today going to be a good day?If you're wondering about these things, you've come to the right place. Every day presents its own set of possibilities, therefore proper planning is required before making a decision.AriesGanesha says, your current job will serve as the cornerstone of your fulfilment.",
        rights: "timesnownews.com",
        rank: 3465,
        topic: "business",
        country: "IN",
        language: "en",
        authors: "Chirag Daruwala,Debosmita Ghosh",
        media:
          "https://static.tnn.in/thumb/msid-96359611,imgsize-100,updatedat-1671509470249,width-1280,height-720,resizemode-75/96359611.jpg",
        is_opinion: false,
        twitter_account: "TIMESNOW",
        _score: 7.2643642,
        _id: "f5cb49e309df6308485948abe3ebd076",
      },
      {
        title:
          "Early signing period: Ranking top 2023 football signing classes after final day",
        author: "Dan Harralson",
        published_date: "2022-12-24 12:42:17",
        published_date_precision: "full",
        link: "https://sports.yahoo.com/early-signing-period-ranking-top-124217224.html",
        clean_url: "yahoo.com",
        excerpt:
          "Early signing period: Ranking the top 2023 football signing classes after the final day",
        summary:
          "The 2022 early signing period took place Dec. 21-23 for the 2023 recruiting signing class.\nThe 2022 early signing period is Josh Heupel's second as Tennessee's head coach. He was hired as the Vols' head coach in Jan. 2021.\n2022 early signing period: Tracking Tennessee's signees\n'It's been a lot of fun going through the process with these guys,' Heupel said Wednesday. 'We believe in, obviously, their athleticism but just as importantly who they are. I'd like to thank their families for entrusting us with their sons for the next three-to-five years.",
        rights: "yahoo.com",
        rank: 31,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Dan Harralson",
        media:
          "https://s.yimg.com/ny/api/res/1.2/yetQXt77uGaLveVNNxybQw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/vols_wire_usa_today_articles_138/795d384bc2f11329193f5ca49ba98bb5",
        is_opinion: false,
        twitter_account: "@Yahoo",
        _score: 7.261834,
        _id: "2546ed43b8d4a1edb98d24b8303554b7",
      },
      {
        title:
          "Where Texas' 2023 recruiting class ranks after the first day of early signing period",
        author: "Cami Griffin",
        published_date: "2022-12-21 21:05:56",
        published_date_precision: "full",
        link: "https://news.yahoo.com/where-texas-2023-recruiting-class-210556338.html",
        clean_url: "yahoo.com",
        excerpt: "Very, very impressive haul for Steve Sarkisian's staff.",
        summary:
          "The first day of the early signing period went extremely well for the Texas Longhorns.\nSteve Sarkisian's staff was able to sign all 21 commits in their 2023 recruiting class on Wednesday. The class is led by five-star quarterback Arch Manning, five-star linebacker Anthony Hill and five-star running back Cedric Baxter Jr.\nThe Longhorns also received somewhat of a surprise recruiting win over Oklahoma for four-star edge Tausili Akana. After Akana's commitment, Texas' 2023 recruiting class jumped one spot in 247Sports' composite team rankings.",
        rights: "yahoo.com",
        rank: 31,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Cami Griffin",
        media:
          "https://s.yimg.com/ny/api/res/1.2/ISk18QHZw6spxKIMdKmOxQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/longhorns_wire_usa_today_articles_557/94605d716ab19023c1a42dbb175d691b",
        is_opinion: false,
        twitter_account: "@YahooNews",
        _score: 7.261383,
        _id: "c58f33550a178a1c19f86670c0035c52",
      },
      {
        title: "Christmas Day closings",
        author: "",
        published_date: "2022-12-23 03:22:00",
        published_date_precision: "full",
        link: "https://www.arkansasonline.com/news/2022/dec/23/christmas-day-closings/",
        clean_url: "arkansasonline.com",
        excerpt:
          "The following state, federal and local government offices' schedules may be affected by the Christmas Day holiday on Sunday.",
        summary:
          "The following state, federal and local government offices' schedules may be affected by the Christmas Day holiday on Sunday.GARBAGE COLLECTIONCammack Village: Regular schedule.Jacksonville: No pickup Monday. Routes will run one day late.Little Rock: No pickup Monday. Routes will run one day late.Little Rock Recycling: No pickup Monday. Routes will run one day late.Maumelle: No pickup today or Monday. Routes will run one day late.North Little Rock: No pickup Monday. Routes will run one day late.Sherwood: No pickup today.",
        rights: "arkansasonline.com",
        rank: 4887,
        topic: "news",
        country: "US",
        language: "en",
        authors: "",
        media:
          "https://wehco.media.clients.ellingtoncms.com/static-4/ao_redesign/graphics/adgog.jpg",
        is_opinion: false,
        twitter_account: "@arkansasonline",
        _score: 7.2586517,
        _id: "e2e9b0710bb5158449ab9286b339b3e3",
      },
      {
        title:
          "Horoscope Today: 20 डिसेंबर; व्यवसायात पैसे गुंतवू नका, ज्येष्ठांचा आदर करा; जाणून घ्या आजचे राशीभविष्य",
        author: "",
        published_date: "2022-12-19 23:30:54",
        published_date_precision: "full",
        link: "https://www.india.com/marathi/lifestyle/horoscope-today-20-december-2022-daily-rashi-bhavishya-in-marathi-aajche-rashifal-5812442/",
        clean_url: "india.com",
        excerpt:
          "Horoscope Today: Rashi Bhavishya, Tuesday, 20 December 2022: आजचं राशीभविष्य, मंगळवार, 20 डिसेंबर; वृषभ राशीच्या लोकांनी व्यवसायात पैसे गुंतवू नका, सिंह लोकांनी वैवाहिक जीवनात मतभेद टाळा, जाणून घ्या…",
        summary:
          "आजचे राशीभविष्य Horoscope Today: Rashi Bhavishya, Tuesday, 20 December 2022: आजचं राशीभविष्य, मंगळवार, 20 डिसेंबर; हा दिवस तुमच्यासाठी कसा असेल? (Daily Rashi Bhavishya in Marathi) कुंडलीतील ग्रहांची स्थिती कशी असेल आणि त्याचा तुमच्यावर काय परिणाम होईल? (Aajche rashifal) तसेच तुमच्यासाठी आजचा शुभ रंग कोणता? (Rashifal in marathi) हे जाणून घ्या ज्योतिष गुरु शिरोमणी सचिनजी यांच्याकडून… मेष (Aries Rashifal Today)\nवैवाहिक जीवनातील समस्या संपेल. वडीलधाऱ्यांचा आशीर्वाद मिळेल. वडिलांची मदत मिळेल. साखर दान करा.",
        rights: "india.com",
        rank: 2337,
        topic: "news",
        country: "IN",
        language: "hi",
        authors: "",
        media:
          "https://static.india.com/wp-content/uploads/2022/11/Rashi-Bhavishya.jpg",
        is_opinion: false,
        twitter_account: "@indiacom",
        _score: 7.2497544,
        _id: "e2359dfd07288d477f80f9cc13367ded",
      },
      {
        title: "How former Alabama players performed in the NFL in Week 15",
        author: "Brody Smoot",
        published_date: "2022-12-20 19:06:26",
        published_date_precision: "full",
        link: "https://sports.yahoo.com/former-alabama-players-performed-nfl-190626366.html",
        clean_url: "yahoo.com",
        excerpt:
          "Check out some of the top former Alabama players from Week 15 of the 2022 NFL season.",
        summary:
          "Alabama has been well-represented at the professional level by players that began their careers in Tuscaloosa. On Sunday, the Tide broke a record for the most players to play in the NFL from one program in a season.\nThat speaks to the culture and foundation that Alabama head coach Nick Saban has established. Times have changed, but the Crimson Tide faithful will likely always be able to see their former favorite players contributing in a positive way to their NFL team's successes.\nRoll Tide Wire breaks down how former Alabama players performed in Week 15 of the 2022 NFL season.",
        rights: "yahoo.com",
        rank: 31,
        topic: "sport",
        country: "US",
        language: "en",
        authors: "Brody Smoot",
        media:
          "https://s.yimg.com/ny/api/res/1.2/TPNvAPBA9wslL8WXJ1aYyQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/roll_tide_wire_usa_today_articles_214/9fda3be12ac6c4419fe4fc836c267db2",
        is_opinion: false,
        twitter_account: "@Yahoo",
        _score: 7.244834,
        _id: "8bcc92b4f8fc5635a4b7afb6ef2e2e4b",
      },
      {
        title:
          "Eagles unofficial depth chart ahead of Week 15 matchup vs. Bears",
        author: "Glenn Erby",
        published_date: "2022-12-17 23:27:52",
        published_date_precision: "timezone unknown",
        link: "https://theeagleswire.usatoday.com/lists/philadelphia-eagles-depth-chart-bears-week-15-dallas-goedert-brett-kern/",
        clean_url: "usatoday.com",
        excerpt:
          "The Bears (3-10) will look to snap a six-game losing streak when they host the NFC-leading Eagles (12-1) Sunday at Soldier Field. Philadelphia will look to take care of business with a showdown…",
        summary:
          "Terms of UsePrivacy PolicyDo Not Sell My InfoHelp CenterAboutUSA TODAY Sports Media GroupThe Bears (3-10) will look to snap a six-game losing streak when they host the NFC-leading Eagles (12-1) Sunday at Soldier Field.Philadelphia will look to take care of business with a showdown against the Cowboys on Christmas Eve looming for Week 16. Chicago will counter with quarterback Justin Fields, who will look to emulate Jalen Hurts' continued improvement with more snaps and game reps. Philadelphia made several rosters moves during the week, but none involved activating star tight end Dallas Goedert.",
        rights: "newsbreak.com",
        rank: 126,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Glenn Erby",
        media:
          "https://img.particlenews.com/img/id/0ifW94_0jmOJu3L00?type=thumbnail_1200x627&limit=20",
        is_opinion: false,
        twitter_account: "@newsbreak",
        _score: 7.2394605,
        _id: "903a4f9e00e30d2af6a751c22192fc3e",
      },
      {
        title:
          "Horoscope Today, December 19: Great day ahead for Cancerians; predictions for all zodiac signs",
        author: "Chirag Daruwala",
        published_date: "2022-12-19 03:00:18",
        published_date_precision: "full",
        link: "https://www.timesnownews.com/astrology/horoscope-today-december-19-great-day-ahead-for-cancerians-predictions-for-all-zodiac-signs-article-96331240",
        clean_url: "timesnownews.com",
        excerpt:
          "Every day presents its own set of possibilities, therefore proper planning is required before making a decision. Before beginning the planning process, you might want to read the astrological…",
        summary:
          "Horoscope for all zodiac signs, December 19, 2022Photo : iStockAre you curious as to what awaits you today? Should you finally say yes to an investment opportunity? Will you be able to purchase your dream home? Is today going to be a good day?If you're wondering about these things, you've come to the right place. Every day presents its own set of possibilities, therefore proper planning is required before making a decision.AriesGanesha says, today, you'll be able to benefit financially significantly.",
        rights: "timesnownews.com",
        rank: 3465,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "Chirag Daruwala,Debosmita Ghosh",
        media:
          "https://static.tnn.in/thumb/msid-96331240,imgsize-100,updatedat-1671418818175,width-1280,height-720,resizemode-75/96331240.jpg",
        is_opinion: false,
        twitter_account: "@TIMESNOW",
        _score: 7.2359104,
        _id: "3075b2139de33a9d3968d3989370378d",
      },
      {
        title: "NFC Playoff Picture: Updated standings going into Week 16",
        author: "Tim Weaver",
        published_date: "2022-12-19 16:00:50",
        published_date_precision: "full",
        link: "https://sports.yahoo.com/nfc-playoff-picture-updated-standings-160050438.html?src=rss",
        clean_url: "yahoo.com",
        excerpt: "Here's where each team stands going into Week 16.",
        summary:
          "The Seahawks were idle after their Thursday night humilation, but the rest of the NFL had a wild weekend, especially among the NFC playoff teams. The Eagles just barely beat the Bears, the Vikings pulled off the largest comeback in league history, the Cowboys lost to the Jaguars in stunning fashion and the red-hot Lions are now knocking loudly on the door for a wild card spot.\nHere's where each team stands going into Week 16.\n1. Philadelphia Eagles (13-1)\nDaniel Bartel-USA TODAY Sports\n2. Minnesota Vikings (11-3)\nMatt Krohn-USA TODAY Sports\n3.",
        rights: "yahoo.com",
        rank: 31,
        topic: "sport",
        country: "US",
        language: "en",
        authors: "Tim Weaver",
        media:
          "https://s.yimg.com/ny/api/res/1.2/.c9IsKUV4shSYCnJCZ2W1A--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/seattle_seahawks_wire_usa_today_sports_articles_798/0211f5e78e10c63846528a6cf382da7b",
        is_opinion: false,
        twitter_account: "@Yahoo",
        _score: 7.2190437,
        _id: "34a5ef0c0edb30df9b034c877bab50d9",
      },
      {
        title: "Eagles' updated 53-man roster for Week 16 matchup at Cowboys",
        author: "Glenn Erby",
        published_date: "2022-12-24 14:23:27",
        published_date_precision: "full",
        link: "https://sports.yahoo.com/eagles-updated-53-man-roster-142327877.html",
        clean_url: "yahoo.com",
        excerpt:
          "Here's an updated look at the Philadelphia Eagles 53-man roster ahead of Saturday afternoon's matchup against the Dallas Cowboys at AT&T Stadium",
        summary:
          "The Philadelphia Eagles are less than seven hours away from returning to the field for a late Saturday afternoon matchup against the Dallas Cowboys at AT&T Stadium.\nThe Birds are the favorite and will look to move to 14-1 on the season while maintaining their lead in the NFC.\nJalen Hurts continues to cement his status for a new contract, and at the same time, Jonathan Gannon's retooled defense has continued to perform down the stretch.\nHere's your updated 53-man roster for Week 16 with Philadelphia choosing to hold quarterback Jalen Hurts out this week.",
        rights: "yahoo.com",
        rank: 31,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Glenn Erby",
        media:
          "https://s.yimg.com/ny/api/res/1.2/fvbYMrEiAa1yBg_AWS6vAQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/philadelphia_eagles_wire_usa_today_sports_articles_352/4e4dac162207f9a5ef5aafee870ae6de",
        is_opinion: false,
        twitter_account: "@Yahoo",
        _score: 7.214667,
        _id: "8e20d8495deea074261c0818c82ed42a",
      },
      {
        title: "Toilet Paper First Sold On This Date In 1857",
        author: "Carmen Angelo",
        published_date: "2022-12-19 15:15:00",
        published_date_precision: "timezone unknown",
        link: "https://wtam.iheart.com/content/2022-12-18-toilet-paper-first-sold-on-this-date-in-1857/",
        clean_url: "iheart.com",
        excerpt:
          "Newsradio WTAM 1100 is Cleveland's only news radio station and an award-winning source of local news.",
        summary:
          'Today in 1776, Thomas Paine published his first "American Crisis" essay, in which he wrote, "These are the times that try men\'s souls." Today in 1857, the first roll of commercially produced toilet paper was sold. Today in 1973, Johnny Carson started a fake toilet-paper scare on the "Tonight Show." In his monologue, he told his huge audience that a Wisconsin congressman had warned that toilet paper was disappearing from supermarket shelves. Due to his gag – it did in many areas of the United States.',
        rights: "iheart.com",
        rank: 799,
        topic: "news",
        country: "US",
        language: "af",
        authors: "Carmen Angelo",
        media:
          "https://i.iheart.com/v3/re/new_assets/632c769eee53c8835b2a0a4e?ops=gravity(%22north%22),fit(1200,675),quality(65)",
        is_opinion: false,
        twitter_account: "@wtam1100",
        _score: 7.1979756,
        _id: "bc776f57761bf1e79cc704f9a5ebc417",
      },
      {
        title: "Elvis Presley Receives Draft Notice On This Date In 1957",
        author: "Carmen Angelo",
        published_date: "2022-12-20 10:30:00",
        published_date_precision: "timezone unknown",
        link: "https://wtam.iheart.com/content/2022-12-19-elvis-presley-receives-draft-notice-on-this-date-in-1957/",
        clean_url: "iheart.com",
        excerpt:
          "Newsradio WTAM 1100 is Cleveland's only news radio station and an award-winning source of local news.",
        summary:
          'Today in 1790, the first successful cotton mill in the United States began operating at Pawtucket, Rhode Island. Today in 1803, the Louisiana Purchase was completed as ownership of the territory was formally transferred from France to the United States during ceremonies in New Orleans. Today in 1843,"A Christmas Carol" by Charles Dickens was first published. It sold out by Christmas Eve. Today in 1957, Elvis Presley received his draft notice. Today in 1980, TV experimented with football as NBC covered the "meaningless" NFL game between the New York Jets (4-11) and the Miami Dolphins (8-7).',
        rights: "iheart.com",
        rank: 799,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Carmen Angelo",
        media:
          "https://i.iheart.com/v3/re/new_assets/632c769eee53c8835b2a0a4e?ops=gravity(%22north%22),fit(1200,675),quality(65)",
        is_opinion: false,
        twitter_account: "@wtam1100",
        _score: 7.1970816,
        _id: "34c7e543af971d32bd55913890ee73ac",
      },
      {
        title: "TAURUS Horoscope Today, December 23, 2022",
        author: "Pandit Jagannath Guruji",
        published_date: "2022-12-22 12:31:00",
        published_date_precision: "full",
        link: "https://www.pinkvilla.com/lifestyle/people/taurus-horoscope-today-december-23-2022-1204426",
        clean_url: "pinkvilla.com",
        excerpt:
          "What message does the alignment of the stars have for Taurus today? Find out from the predictions below.",
        summary:
          "You wake up today and will realize that you're having the urge to take a trip today. Analyze how much pendency you're having on your bucket list. If there are no major projects that require your attention today, you can surely plan a small trip today with your close ones or family members. Thanks to your enthusiasm, you will be making some detailed plans and arrangements today, which will reap benefits in days to come. On the health front, offering your mind mental peace is highly recommended today.",
        rights: "pinkvilla.com",
        rank: 11121,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "Pandit Jagannath Guruji",
        media:
          "https://www.pinkvilla.com/english/images/2022/12/227064918_2_1280*720.jpg",
        is_opinion: false,
        twitter_account: "@pinkvilla",
        _score: 7.195547,
        _id: "c3a602518c8aa4e667d598ae2a83e536",
      },
      {
        title: "NFL Week 16 announcers schedule revealed",
        author: "Barry Werner",
        published_date: "2022-12-21 19:35:18",
        published_date_precision: "full",
        link: "https://touchdownwire.usatoday.com/lists/nfl-week-16-announcers-schedule-revealed/",
        clean_url: "usatoday.com",
        excerpt:
          "What NFL announcers will be working the games on Christmas Eve and Christmas?",
        summary:
          "USAT\nAmazon Prime Video: Al Michaels, Kirk Herbstreit, Kaylee Hartung Eric Hartline-USA TODAY Sports\nFOX: Kenny Albert, Jonathan Vilma, Shannon Spake (Photo by Nic Antaya/Getty Images)\nFOX: Chris Myers, Robert Smith, Jen Hale Jamie Sabau-USA TODAY Sports\nCBS: Greg Gumbel, Adam Archuleta, AJ Ross Akron Beacon Journal\nCBS: Spero Dedes, Jay Feely, Aditi Kinkhabwala E(Photo by Jeff Zelevansky/Getty Images)\n FOX: Kevin Kugler, Mark Sanchez, Laura Okmin Kirby Lee-USA TODAY Sports\nFOX: Adam Amin, Mark S",
        rights: "usatoday.com",
        rank: 126,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Barry Werner,Doug Farrar,Nfl Wire,Pm Et",
        media:
          "https://touchdownwire.usatoday.com/wp-content/uploads/sites/59/2022/12/1002161282.jpg?w=1024&h=576&crop=1",
        is_opinion: false,
        twitter_account: null,
        _score: 7.1867013,
        _id: "4e7bec2a5dc7b3093501f6c312c7d19f",
      },
      {
        title: "NFL Week 15: Former Vols' stats",
        author: "Ken Lay",
        published_date: "2022-12-20 15:18:19",
        published_date_precision: "full",
        link: "https://sports.yahoo.com/nfl-week-15-former-vols-151819956.html?src=rss",
        clean_url: "yahoo.com",
        excerpt:
          "A look at how former Vols performed in Week 15 of the 2022 NFL season.",
        summary:
          "Week 15 of the 2022 National Football League season has concluded.\nThe 2022 NFL season will conclude Feb. 12, 2023 with Super Bowl LVII. Super Bowl LVII will be played at State Farm Stadium in Glendale, Arizona.\nWeek 16 games will be contested Dec. 22-26.\nNFL Week 14: Former Vols' stats\nNFL Week 13: Former Vols' stats\nNFL Week 12: Former Vols' stats\nNFL Week 11: Former Vols' stats\nNFL Week 10: Former Vols' stats\nNFL Week 9: Former Vols' stats\nNFL Week 8: Former Vols' stats\nNFL Week 7: Former Vols' stats\nNFL Week 6: Former Vols' stats\nNFL Week 5: Former Vols' stats\nNFL Week 4: Former Vols' stats\nNFL Week 3: Former Vols' stats\nNFL Week 2: Former Vols' stats\nNFL Week 1: Former Vols' stats\nNFL preseason Week 3: Former Vols' stats\nNFL preseason Week 2: Former Vols' stats\nNFL preseason Week 1: Former Vols' stats\nEach week, Vols Wire looks at stats for former University of Tennessee players in the NFL.",
        rights: "yahoo.com",
        rank: 31,
        topic: "sport",
        country: "US",
        language: null,
        authors: "Ken Lay",
        media:
          "https://s.yimg.com/ny/api/res/1.2/LERSjfecBTVMcwVyV6Bxkw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/vols_wire_usa_today_articles_138/ea7f23a66b0c9cbd1bef4babe7ce3267",
        is_opinion: false,
        twitter_account: "@Yahoo",
        _score: 7.1864033,
        _id: "1dd8eba4cae66c019c4ff7333ed9bcf2",
      },
      {
        title:
          "Numerology Prediction December 19: Expert predicts Monday for you",
        author: "DNA Web Team",
        published_date: "2022-12-19 02:00:00",
        published_date_precision: "timezone unknown",
        link: "https://www.dnaindia.com/lifestyle/report-numerology-prediction-numerology-expert-prediction-lucky-number-lucky-colour-prediction-monday-3011645",
        clean_url: "dnaindia.com",
        excerpt: "See your lucky number and lucky colour for December 19.",
        summary:
          "Numerology prediction December 19 | Photo: PixabayToday 19th December 2022 day is Monday. What will be the effect of the combination of planets being formed on this day and the condition of stars on you? How will your day be for you, know from Guru Kkomal Vasisht. Know how today is going to be for you Number 1 – (Birth Date 1, 10, 19, 28 in any month) Today your luck will support you completely. You will get new options for progress; it is necessary to keep some restraint on your anger and arrogance.",
        rights: "dnaindia.com",
        rank: 2816,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "DNA Web Team",
        media:
          "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2022/12/19/2561478-untitled-design-2022-08-25t224621.163.jpg",
        is_opinion: false,
        twitter_account: "@dna",
        _score: 7.1862936,
        _id: "34c821b7ae238351b32b8dfee5fa7b2e",
      },
      {
        title: "CANCER Horoscope Today, December 23, 2022",
        author: "Pandit Jagannath Guruji",
        published_date: "2022-12-22 12:31:05",
        published_date_precision: "full",
        link: "https://www.pinkvilla.com/lifestyle/people/cancer-horoscope-today-december-23-2022-1204428",
        clean_url: "pinkvilla.com",
        excerpt:
          "What message does the alignment of the stars have for Cancer today? Find out from the predictions below.",
        summary:
          "It's one of those days when you'll be at your inventive best today. As a result, you will taste success in every field associated with you. Also, you'll find that your loved ones back at home might be waiting for you today to spend some quality time with you. Remember that it will be your experience that will be reaping benefits for your future. If you're a beginner, it's obvious that you will be facing a lot of issues today. On the health front, sensitivity in your teeth can be a problem today.  Cancer Love Horoscope Today Your relationship will be under strain today.",
        rights: "pinkvilla.com",
        rank: 11121,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "Pandit Jagannath Guruji",
        media:
          "https://www.pinkvilla.com/english/images/2022/12/1226554456_4_1280*720.jpg",
        is_opinion: false,
        twitter_account: "@pinkvilla",
        _score: 7.183686,
        _id: "4a2182f49a7861234f2907831c57cc20",
      },
      {
        title: "11 Alabama players named to NFL Pro Bowl rosters",
        author: "Aj Spurr",
        published_date: "2022-12-22 10:11:33",
        published_date_precision: "full",
        link: "https://rolltidewire.usatoday.com/lists/alabama-in-the-nfl-2022-pro-bowl-roster-afc-nfc/",
        clean_url: "usatoday.com",
        excerpt: "Alabama is well represented in the NFL Pro Bowl",
        summary:
          "Alabama football is known for winning championships and producing star talent at the next level. There's no better way to display how successful the former Crimson Tide players are in the NFL than seeing how many made the annual Pro Bowl.\nThis year, the NFL is not hosting a Pro Bowl game, but will instead host numerous small games in hopes of improving fan viewership.\nBuy Crimson Tide Tickets\nIn total, 11 former Alabama players were selected to both the AFC and NFC rosters. With both the offense and defense represented, there aren't too many surprises.",
        rights: "usatoday.com",
        rank: 126,
        topic: "news",
        country: "US",
        language: "en",
        authors: "AJ Spurr,Am Ct,Brody Smoot,Sam Murphy",
        media:
          "https://rolltidewire.usatoday.com/wp-content/uploads/sites/15/2022/11/1437759340.jpg?w=1024&h=576&crop=1",
        is_opinion: false,
        twitter_account: null,
        _score: 7.181566,
        _id: "b327a650223b3e3fd16bdf6aea0897c6",
      },
      {
        title: "Auburn Basketball falls out of latest ESPN BPI top 25",
        author: "Taylor Jones",
        published_date: "2022-12-20 14:00:54",
        published_date_precision: "full",
        link: "https://auburnwire.usatoday.com/lists/auburn-basketball-espn-bpi-tigers-fall-out-of-top-25-bruce-pearl-johni-broome-allen-flanigan/",
        clean_url: "usatoday.com",
        excerpt:
          "Auburn took quite a tumble in rankings following its' loss to USC on Sunday.",
        summary:
          "Auburn suffered its second loss of the season last Sunday, taking a 74-71 defeat at USC in Los Angeles.\nBecause of the loss, Auburn fell several places in both the Associated Press poll, as well as the USA TODAY coaches poll. Despite dropping several places in both polls, as well as the KenPom, the Tigers failed to have such luck with the Basketball Power Index from ESPN.\nBuy Tigers Tickets\nAfter Sunday's loss, Auburn has fallen to No. 28 overall, a seven-spot drop from last week's rankings. The win moved USC up to spaces to No.",
        rights: "usatoday.com",
        rank: 126,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Jd Mccarthy,Pm Ct,River Wells,Taylor Jones",
        media:
          "https://auburnwire.usatoday.com/wp-content/uploads/sites/14/2022/12/USATSI_19648857.jpg?w=1024&h=576&crop=1",
        is_opinion: false,
        twitter_account: null,
        _score: 7.180181,
        _id: "1cfc46cc2422343b22cc61a213fa0a4b",
      },
      {
        title: "SEA Today Run 2022 Event Lari Favorit di Penghujung Tahun 2022",
        author: "Toni Bramantoro",
        published_date: "2022-12-19 09:47:21",
        published_date_precision: "full",
        link: "https://www.tribunnews.com/sport/2022/12/19/sea-today-run-2022-event-lari-favorit-di-penghujung-tahun-2022",
        clean_url: "tribunnews.com",
        excerpt:
          "Sejak sebelum pandemi, olahraga lari tak hanya menjadi trend namun sudah menjadi lifestyle di kalangan masyarakat urban yang memiliki gaya hidup",
        summary:
          "lihat foto Dok. pribadiSEA Today Run 2022 Menjadi Event Lari Favorit di Penghujung Tahun 2022  TRIBUNNEWS.COM, JAKARTA - Sejak sebelum pandemi, olahraga lari tak hanya menjadi trend namun sudah menjadi lifestyle di kalangan masyarakat urban yang memiliki gaya hidup sehat.\nBerbagai event yang melibatkan pelari profesional maupun komunitas pelari sudah sering digelar. Baru-baru ini SEA Today menggelar event SEA Today Run 2022 di penghujung tahun 2022 yang disambut antusias para pecinta olahraga lari dari dalam dan luar negeri.",
        rights: "2022 Tribunnews.com",
        rank: 5860,
        topic: "news",
        country: "ID",
        language: "id",
        authors: "Toni Bramantoro",
        media:
          "https://cdn-2.tstatic.net/tribunnews/foto/bank/images/sea-today-run-2022-menjadi-event-lari-favorit-di-penghujung-tahun-2022.jpg",
        is_opinion: false,
        twitter_account: null,
        _score: 7.177012,
        _id: "7041738c765e31c2257bf375831c0d78",
      },
      {
        title: "MCQUATTRO",
        author: "",
        published_date: "2022-12-21 12:45:00",
        published_date_precision: "timezone unknown",
        link: "https://mcquattro.skyrock.com/profil/",
        clean_url: "skyrock.com",
        excerpt:
          "I am engaged in creating music, I have a rather unusual style. I post my music on various platforms, including YouTube and pixabay. You can listen to my tracks and like them if you are inspired!…",
        summary:
          "The position of the blocks have been saved.     Today at 5:07 AM BEATS BEATS (MC QUATTRO) UFO RAGE (cyberpunk theme) \n   Today at 5:06 AM BEATS BEATS MC QUATTRO must be destroyed (ufo revenge) \n   Today at 5:06 AM MC QUATTRO Back to the Future retrowave punk \n   Today at 5:06 AM MC QUATTRO - an old music cassette (Retrowawe, Synthwawe) \n   Today at 5:06 AM MC QUATTRO - epic chase",
        rights: "skyrock.com",
        rank: 1619,
        topic: "news",
        country: "FR",
        language: null,
        authors: "",
        media: "https://mgl.skyrock.net/art/PRIP.124326107.3.2.jpg",
        is_opinion: false,
        twitter_account: null,
        _score: 7.1750107,
        _id: "6c9b91d2f9946445efb3444596a48f5d",
      },
      {
        title:
          "I'm ill but have a job interview (online) today so did a natural (for me) look today! Wish me luck :)",
        author: "/u/HoneyyBadgers",
        published_date: "2022-12-19 11:24:58",
        published_date_precision: "full",
        link: "https://www.reddit.com/r/MakeupAddiction/comments/zpp0va/im_ill_but_have_a_job_interview_online_today_so",
        clean_url: "reddit.com",
        excerpt:
          "3.7m members in the MakeupAddiction community. The subreddit for everything makeup related.",
        summary:
          "I'm ill but have a job interview (online) today so did a natural (for me) look today! Wish me luck :)",
        rights: "reddit.com",
        rank: 39,
        topic: "beauty",
        country: "US",
        language: "en",
        authors: "/u/HoneyyBadgers",
        media:
          "https://preview.redd.it/t97bvzgbsv6a1.jpg?auto=webp&s=2218dd0efc2973f54f113f8f251fae5152fccd5c",
        is_opinion: false,
        twitter_account: "@reddit",
        _score: 7.1663,
        _id: "89eee4e9ac230f0a9797af98549b512f",
      },
      {
        title:
          "2022 SEC offenses by the numbers for first downs in league games",
        author: "Dan Harralson",
        published_date: "2022-12-19 10:19:04",
        published_date_precision: "full",
        link: "https://volswire.usatoday.com/lists/2022-sec-football-offenses-by-the-numbers-for-first-downs-in-league-games/",
        clean_url: "usatoday.com",
        excerpt:
          "A look at 2022 SEC offenses by the numbers for first downs in league-only games.",
        summary:
          "No. 6 Tennessee (10-2, 6-2 SEC) will play No. 7 Clemson (11-2, 8-0 ACC) in the Capital One Orange Bowl on Dec. 30.\nKickoff between the Vols and Tigers is slated for 8 p.m. EST (ESPN) at Hard Rock Stadium in Miami Gardens, Florida.\nBuy Volunteers Tickets\nTennessee's 2022 regular-season schedule featured home games against Ball State (W, 59-10), Akron (W, 63-6), Florida (W, 38-33), Alabama (W, 52-49), UT Martin (W, 65-24), Kentucky (W, 44-6) and Missouri (W, 66-24).\nThe Vols' 2022 schedule featured road contests at Pittsburgh (W, 34-27 OT) in the second edition of the Johnny Majors Classic, LSU (W, 40-13), Georgia (L, 27-13), South Carolina (L, 63-38) and Vanderbilt (W, 56-0).",
        rights: "usatoday.com",
        rank: 126,
        topic: "news",
        country: "US",
        language: "en",
        authors: "Am Et,Dan Harralson",
        media:
          "https://volswire.usatoday.com/wp-content/uploads/sites/19/2022/09/USATSI_19069720.jpg?w=1024&h=576&crop=1",
        is_opinion: false,
        twitter_account: null,
        _score: 7.159612,
        _id: "265e0470d4a8fbbf0ebe09623ba9136c",
      },
      {
        title: "Lenovo Legion 5 BSoDs",
        author: "",
        published_date: "2022-12-20 08:25:14",
        published_date_precision: "full",
        link: "https://www.bleepingcomputer.com/forums/t/780518/lenovo-legion-5-bsods/",
        clean_url: "bleepingcomputer.com",
        excerpt:
          "Page 1 of 2 - Lenovo Legion 5 BSoDs - posted in Windows Crashes and Blue Screen of Death (BSOD) Help and Support: Hi recently a Lenovo Legion 5 (15ARH05H) laptop is experiencing BSoDs, and here are…",
        summary:
          "Posted Today, 02:06 AM\n\n\nHi recently a Lenovo Legion 5 (15ARH05H) laptop is experiencing BSoDs, and here are the dump files and the specs of the machine itself: Ryzen 7 4800H\n2x8GB DDR4 3200MHz\n512GB Samsung SSD (MZVLB512HBJQ-000L2)\nRTX2060\nIntel AX200 wireless\nWindows 10 Home Single Language 21H2 The results from WinDBG are not helping much either \nAttached Files\n\n\n\n dmp.zip   1.63MB\n  1 downloads\n\n \n\nEdited by recomputeme, Today, 02:25 AM.\n\n \n\n \n\n \n\nPosted Today, 02:26 AM\n\n\nHi, Welcome to BC. Please Post the Collection here as per Posting Instructions : https://www.",
        rights: "bleepingcomputer.com",
        rank: 1684,
        topic: "news",
        country: "US",
        language: "en",
        authors: "",
        media:
          "https://www.bleepingcomputer.com/forums/public/style_images/master/meta_image.png",
        is_opinion: false,
        twitter_account: null,
        _score: 7.159148,
        _id: "65373b4386484cebc731cb994ff57715",
      },
      {
        title:
          "Numerology Prediction December 24: From green to golden, these colours will be lucky for you today",
        author: "DNA Web Team",
        published_date: "2022-12-24 02:15:00",
        published_date_precision: "timezone unknown",
        link: "https://www.dnaindia.com/lifestyle/report-numerology-prediction-december-24-numerology-expert-predicts-expert-prediction-lucky-colour-lucky-number-3012677",
        clean_url: "dnaindia.com",
        excerpt: "Check numerology prediction for December 24 here.",
        summary:
          "Numerology Prediction December 24 | Photo: PixabayToday 24th December 2022 day is Saturday. What will be the effect of the combination of planets being formed on this day and the condition of stars on you? How will your day be for you, know from Guru Kkomal Vasisht.  Know how today is going to be for you Number 1 – (Birth Date 1, 10, 19, 28 in any month) Today there will be a mixed effect. There may be differences with the father. Life partner will get support. New work can be started. Mental dilemmas and troubles can also be faced.",
        rights: "dnaindia.com",
        rank: 2816,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "DNA Web Team",
        media:
          "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2022/12/24/2562427-untitled-design-2022-09-06t223505.726.jpg",
        is_opinion: false,
        twitter_account: "@dna",
        _score: 7.157689,
        _id: "10c741868f971d775b95875a427ec952",
      },
      {
        title: "AQUARIUS Horoscope Today, December 24, 2022",
        author: "Pandit Jagannath Guruji",
        published_date: "2022-12-23 15:32:08",
        published_date_precision: "full",
        link: "https://www.pinkvilla.com/lifestyle/people/aquarius-horoscope-today-december-24-2022-1204557",
        clean_url: "pinkvilla.com",
        excerpt:
          "How do you think Aquarius's day looks like today? Read the predictions below to find out.",
        summary:
          "Nothing but money will be revolving in your head today. Apart from balancing both your personal and professional life, you'll be searching for opportunities for making good profits today. Though, it is advised that you shouldn't plan to invest in long-term assets for now. Rather, you can consider postponing it if there's an idea in your head. Uplift your confidence by considering each day as God's blessing. Talking about health, you're advised to take proper care of elderly members of your family who are close to you.",
        rights: "pinkvilla.com",
        rank: 11121,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "Pandit Jagannath Guruji",
        media:
          "https://www.pinkvilla.com/english/images/2022/12/664721612_11_1280*720.jpg",
        is_opinion: false,
        twitter_account: "@pinkvilla",
        _score: 7.1560516,
        _id: "46dab112f2fe121f76db1d6474c2089f",
      },
      {
        title:
          "Rashifal Today 20 Dec: कैसा रहेगा आज आपका दिन! क्या कहते हैं आपके सितारे? जानें…",
        author: "",
        published_date: "2022-12-20 01:30:00",
        published_date_precision: "timezone unknown",
        link: "https://www.india.com/hindi-news/faith-hindi/rashifal-20-december-leo-virgo-libra-aries-taurus-gemini-scorpio-sagittarius-capricorn-aquarius-pisces-rashifal-today-20-dec-horoscope-5812431/",
        clean_url: "india.com",
        excerpt:
          "Aaj Ka Rashifal 20 Dec: आज 20 दिसंबर 2022, दिन मंगलवार है. कैसा रहेगा आपका आज का दिन, क्या है आपके सितारों की चाल और इसका आप पर क्या होगा असर, जानें एस्ट्रो गुरु पंडित शिरोमणि सचिन से...",
        summary:
          "आज का राशिफल Aaj Ka Rashifal 20 Dec: आज 20 दिसंबर 2022, दिन मंगलवार है. कैसा रहेगा आपका आज का दिन, क्या है आपके सितारों की चाल और इसका आप पर क्या होगा असर, जानें एस्ट्रो गुरु पंडित शिरोमणि सचिन से…\nजानें अपनी राशि का हाल\nमेष (Aries Rashifal Today)\nविवाह की समस्या खत्म होगी. अपने से बड़ों का आशीर्वाद मिलेगा. पिता से मदद मिलेगी. शक्कर का दान दें.\nशुभ रंग: लाल\nवृष (Today Taurus Rashifal)\nपारिवारिक समस्या खड़ी होगी. व्यापार में पैसा न लगाएं. बुजुर्गों का आदर करें. जरूरतमंद लोगों को दान दें.\nशुभ रंग: गुलाबी\nमिथुन (Today Gemini Rashifal)\nआर्थिक समस्या खत्म होगी.",
        rights: "india.com",
        rank: 2337,
        topic: "news",
        country: "IN",
        language: null,
        authors: "",
        media:
          "https://static.india.com/wp-content/uploads/2022/07/Aaj-Ka-Rashifal.jpg",
        is_opinion: false,
        twitter_account: "@indiacom",
        _score: 7.155692,
        _id: "4b086d897ea9c8b6d391402dd1f9e37e",
      },
      {
        title: "LIBRA Horoscope Today, December 23, 2022",
        author: "Pandit Jagannath Guruji",
        published_date: "2022-12-22 12:31:11",
        published_date_precision: "full",
        link: "https://www.pinkvilla.com/lifestyle/people/libra-horoscope-today-december-23-2022-1204431",
        clean_url: "pinkvilla.com",
        excerpt:
          "What message does the alignment of the stars have for Libra today? Find out from the predictions below.",
        summary:
          "Dear Libras, children are assumed to be the ultimate source of appreciation today for you. Your logical attributes will turn stronger as the day progresses ahead. Try to remain calm and with peace today; you will be able to make good decisions, supporting and favoring your future. Also, you can consider flowing with the tide while enjoying the moments coming with them. Regardless of what happens today, do not stress your mind; it can leave a negative impact on you.  Libra Love Horoscope Today Your partner may be convincing you today to go out somewhere since it has been a long time.",
        rights: "pinkvilla.com",
        rank: 11121,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "Pandit Jagannath Guruji",
        media:
          "https://www.pinkvilla.com/english/images/2022/12/74610735_7_1280*720.jpg",
        is_opinion: false,
        twitter_account: "@pinkvilla",
        _score: 7.1552224,
        _id: "e33439e4c54e2613de331c790618a635",
      },
      {
        title: "CAPRICORN Horoscope Today, December 24, 2022",
        author: "Pandit Jagannath Guruji",
        published_date: "2022-12-23 15:32:06",
        published_date_precision: "full",
        link: "https://www.pinkvilla.com/lifestyle/people/capricorn-horoscope-today-december-24-2022-1204556",
        clean_url: "pinkvilla.com",
        excerpt:
          "How do you think Capricorn's day looks like today? Read the predictions below to find out.",
        summary:
          "You don't really have to worry much about your professional state today. Looking at the stars, things will be favoring you where you shall be completing your work on time. Despite achieving results, you may not be that satisfied with how your work is currently progressing. Chances are there you might be lacking the kind of joy you're expecting from the job. Going through stress and tension can be common during this time. Therefore, you are advised to focus on meditation for keeping yourself relaxed and calm.",
        rights: "pinkvilla.com",
        rank: 11121,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "Pandit Jagannath Guruji",
        media:
          "https://www.pinkvilla.com/english/images/2022/12/1363989344_10_1280*720.jpg",
        is_opinion: false,
        twitter_account: "@pinkvilla",
        _score: 7.154017,
        _id: "f32366a3a0ebc7c52278e1a6644ed6c9",
      },
      {
        title: "VIRGO Horoscope Today, December 24, 2022",
        author: "Pandit Jagannath Guruji",
        published_date: "2022-12-23 15:31:58",
        published_date_precision: "full",
        link: "https://www.pinkvilla.com/lifestyle/people/virgo-horoscope-today-december-24-2022-1204552",
        clean_url: "pinkvilla.com",
        excerpt:
          "How do you think Virgo's day looks like today? Read the predictions below to find out.",
        summary:
          "You are probably going to remain happy in whatever things you'll be doing today. Harmony and peace can be seen on the domestic front, which will provide you with a sigh of relief. Consider spending more time with your parents as they might need you emotionally today. Take good care of them since they're getting old now. Ensure that they are at peace and comfort, both mentally and physically, which is your rightful duty. On the health front, you might have to deal with an upset stomach later in the day today.",
        rights: "pinkvilla.com",
        rank: 11121,
        topic: "news",
        country: "IN",
        language: "en",
        authors: "Pandit Jagannath Guruji",
        media:
          "https://www.pinkvilla.com/english/images/2022/12/157485976_6_1280*720.jpg",
        is_opinion: false,
        twitter_account: "@pinkvilla",
        _score: 7.154017,
        _id: "176bef86aecf79f45dcc4ef995287707",
      },
    ],
    user_input: {
      q: "today",
      search_in: ["title_summary"],
      lang: null,
      not_lang: null,
      countries: null,
      not_countries: null,
      from: "2022-12-17 00:00:00",
      to: null,
      ranked_only: "True",
      from_rank: null,
      to_rank: null,
      sort_by: "relevancy",
      page: 1,
      size: 50,
      sources: null,
      not_sources: null,
      topic: null,
      published_date_precision: null,
    },
  },
};
